[book]
title = "Program Learning"
authors = ["Yuan Chang"]
description = "程式入門"

[rust]
edition = "2018"

[build]
build-dir = "book"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[output.html]

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true
